### ISSUE TITLE
gah module dependency remove error

### ISSUE THREAD

**Issue by samateja** [awdware/gah#17]
gah v0.0.75

√ Select one or multiple dependencies to remove · presentation
 ■ TypeError: Cannot read property 'names' of undefined
TypeError: Cannot read property 'names' of undefined
    at _loop_1 (C:\Users\max.musterman\AppData\Roaming\npm\node_modules\@awdware\gah\lib\controller\dependency.controller.js:99:37)
    at DependencyController.<anonymous> (C:\Users\venkata.sama\AppData\Roaming\npm\node_modules\@awdware\gah\lib\controller\dependency.controller.js:110:29)
    at step (C:\Users\max.musterman\AppData\Roaming\npm\node_modules\@awdware\gah\lib\controller\dependency.controller.js:52:23)
    at Object.next (C:\Users\max.musterman\AppData\Roaming\npm\node_modules\@awdware\gah\lib\controller\dependency.controller.js:33:53)
    at fulfilled (C:\Users\max.musterman\AppData\Roaming\npm\node_modules\@awdware\gah\lib\controller\dependency.controller.js:24:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by LoaderB0T** [comment]
Thanks for the issue I can confirm this is a bug
